import React, { useState, useEffect } from 'react';
import type { ServiceType, BillRecord } from '../types';
import { useCalculator } from '../hooks/useCalculator';
import { Save, RefreshCw, AlertCircle, History, Upload, FileText, X } from 'lucide-react';
import Swal from 'sweetalert2';
import { supabase } from '../lib/supabase';

interface CalculatorFormProps {
    selectedService: ServiceType;
    onSave: (record: BillRecord) => void;
    fetchLatestReadings: () => Promise<{ street: number; internal: number }>;
}

export const CalculatorForm: React.FC<CalculatorFormProps> = ({ selectedService, onSave, fetchLatestReadings }) => {
    const { calculateSplit } = useCalculator();

    // Readings State
    const [period, setPeriod] = useState<string>('');
    const [amount, setAmount] = useState<string>('');

    // Street Meter Readings
    const [streetPrev, setStreetPrev] = useState<string>('');
    const [streetCurr, setStreetCurr] = useState<string>('');

    // Internal Meter Readings
    const [internalPrev, setInternalPrev] = useState<string>('');
    const [internalCurr, setInternalCurr] = useState<string>('');

    // File Upload
    const [file, setFile] = useState<File | null>(null);
    const [uploading, setUploading] = useState(false);

    // Auto-fetch readings when service changes
    useEffect(() => {
        const loadReadings = async () => {
            const { street, internal } = await fetchLatestReadings();
            if (street > 0) setStreetPrev(street.toString());
            if (internal > 0) setInternalPrev(internal.toString());
            // Clear currents
            setStreetCurr('');
            setInternalCurr('');
        };
        loadReadings();
    }, [selectedService, fetchLatestReadings]);

    // Calculate Consumptions
    const streetDiff = Math.max(0, (parseFloat(streetCurr) || 0) - (parseFloat(streetPrev) || 0));
    const internalDiff = Math.max(0, (parseFloat(internalCurr) || 0) - (parseFloat(internalPrev) || 0));

    const result = calculateSplit(
        parseFloat(amount) || 0,
        streetDiff,
        internalDiff
    );

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            const selected = e.target.files[0];
            if (selected.type !== 'application/pdf') {
                Swal.fire({ icon: 'error', title: 'Solo PDF', text: 'Por favor sube un archivo PDF' });
                return;
            }
            setFile(selected);
        }
    };

    const handleSave = async () => {
        if (!amount || !streetCurr || !streetPrev || !internalCurr || !internalPrev || !period) {
            Swal.fire({
                icon: 'error',
                title: 'Faltan datos',
                text: 'Por favor completa todas las lecturas',
                confirmButtonColor: '#3b82f6'
            });
            return;
        }

        if (streetDiff <= 0) {
            Swal.fire({
                icon: 'warning',
                title: 'Revisar Lecturas',
                text: 'El consumo total es 0 o negativo. Revisa que la lectura actual sea mayor a la anterior.',
            });
            return;
        }

        let fileUrl = undefined;
        if (file) {
            setUploading(true);
            const fileName = `${Date.now()}_${file.name.replace(/\s+/g, '_')}`;
            const { data, error } = await supabase.storage
                .from('bills')
                .upload(fileName, file);

            setUploading(false);

            if (error) {
                console.error('Upload error:', error);
                Swal.fire({ icon: 'error', title: 'Error al subir', text: 'No se pudo subir la factura. Intenta de nuevo o guarda sin archivo.' });
                return;
            }

            if (data) {
                const { data: publicUrlData } = supabase.storage.from('bills').getPublicUrl(fileName);
                fileUrl = publicUrlData.publicUrl;
            }
        }

        const record: BillRecord = {
            // id will be generated by Supabase or handled by hook,
            // but we need a temp one for interface compliance if strict
            id: crypto.randomUUID(),
            type: selectedService,
            date: new Date().toISOString(),
            periodLabel: period,
            billAmount: parseFloat(amount),
            totalConsumption: streetDiff,
            backHouseConsumption: internalDiff,
            frontHouseConsumption: result.frontCons,
            streetReadingPrev: parseFloat(streetPrev),
            streetReadingCurr: parseFloat(streetCurr),
            internalReadingPrev: parseFloat(internalPrev),
            internalReadingCurr: parseFloat(internalCurr),
            frontHousePay: result.frontPayRounded,
            backHousePay: result.backPayRounded,
            isPaid: false,
            fileUrl: fileUrl
        };

        onSave(record);

        // Clear Form
        setAmount('');
        setStreetPrev(streetCurr); // Set current as next previous
        setStreetCurr('');
        setInternalPrev(internalCurr); // Set current as next previous
        setInternalCurr('');
        setPeriod('');
        setFile(null);

        Swal.fire({
            icon: 'success',
            title: 'Guardado',
            text: 'Registro guardado.',
            timer: 2000,
            showConfirmButton: false
        });
    };

    const handleClear = () => {
        setAmount('');
        setStreetPrev('');
        setStreetCurr('');
        setInternalPrev('');
        setInternalCurr('');
        setPeriod('');
        setFile(null);
    };

    const unit = selectedService === 'GAS' ? 'm³' : 'kWh';

    return (
        <div className="bg-white rounded-2xl shadow-lg p-6 mb-8">
            <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
                <span className="bg-gray-100 p-2 rounded-lg">
                    Calculadora de {selectedService === 'GAS' ? 'Gas' : 'Luz'}
                </span>
            </h3>

            <div className="space-y-6">
                {/* Basic Info */}
                <div className="grid grid-cols-2 gap-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Periodo</label>
                        <input
                            type="text"
                            value={period}
                            onChange={(e) => setPeriod(e.target.value)}
                            className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                            placeholder="Ene-Feb"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Monto ($)</label>
                        <input
                            type="number"
                            value={amount}
                            onChange={(e) => setAmount(e.target.value)}
                            className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all font-mono"
                            placeholder="0.00"
                        />
                    </div>
                </div>

                {/* File Upload */}
                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Adjuntar Factura (PDF)</label>
                    {!file ? (
                        <div className="relative border-2 border-dashed border-gray-300 rounded-xl p-4 hover:bg-gray-50 transition-colors text-center cursor-pointer">
                            <input
                                type="file"
                                accept="application/pdf"
                                onChange={handleFileChange}
                                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                            />
                            <div className="flex flex-col items-center gap-1 text-gray-500">
                                <Upload size={20} />
                                <span className="text-xs">Toca para subir PDF</span>
                            </div>
                        </div>
                    ) : (
                        <div className="flex items-center justify-between bg-blue-50 p-3 rounded-xl border border-blue-100">
                            <div className="flex items-center gap-2 overflow-hidden">
                                <div className="bg-white p-1.5 rounded text-red-500 shadow-sm">
                                    <FileText size={16} />
                                </div>
                                <span className="text-sm text-blue-900 truncate">{file.name}</span>
                            </div>
                            <button
                                onClick={() => setFile(null)}
                                className="text-gray-400 hover:text-red-500 p-1"
                            >
                                <X size={16} />
                            </button>
                        </div>
                    )}
                </div>

                <div className="border-t border-gray-100 my-4"></div>

                {/* Meters Section */}
                <div className="space-y-4">
                    {/* Street Meter */}
                    <div className="bg-blue-50 p-4 rounded-xl border border-blue-100">
                        <div className="flex items-center gap-2 mb-3">
                            <History size={16} className="text-blue-500" />
                            <h4 className="font-semibold text-blue-900 text-sm">Medidor Calle (Total)</h4>
                        </div>
                        <div className="grid grid-cols-2 gap-3">
                            <div>
                                <label className="text-xs text-gray-500 block mb-1">Anterior</label>
                                <input
                                    type="number"
                                    value={streetPrev}
                                    onChange={(e) => setStreetPrev(e.target.value)}
                                    className="w-full p-2 rounded border border-blue-200 focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm"
                                    placeholder="Ej. 1000"
                                />
                            </div>
                            <div>
                                <label className="text-xs text-gray-500 block mb-1">Actual</label>
                                <input
                                    type="number"
                                    value={streetCurr}
                                    onChange={(e) => setStreetCurr(e.target.value)}
                                    className="w-full p-2 rounded border border-blue-200 focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm"
                                    placeholder="Ej. 1100"
                                />
                            </div>
                        </div>
                        <div className="mt-2 text-right">
                            <span className="text-xs font-medium text-blue-600">Consumo: {streetDiff} {unit}</span>
                        </div>
                    </div>

                    {/* Internal Meter */}
                    <div className="bg-orange-50 p-4 rounded-xl border border-orange-100">
                        <div className="flex items-center gap-2 mb-3">
                            <History size={16} className="text-orange-500" />
                            <h4 className="font-semibold text-orange-900 text-sm">Medidor Interno (Atrás)</h4>
                        </div>
                        <div className="grid grid-cols-2 gap-3">
                            <div>
                                <label className="text-xs text-gray-500 block mb-1">Anterior</label>
                                <input
                                    type="number"
                                    value={internalPrev}
                                    onChange={(e) => setInternalPrev(e.target.value)}
                                    className="w-full p-2 rounded border border-orange-200 focus:outline-none focus:ring-2 focus:ring-orange-500 text-sm"
                                    placeholder="Ej. 50"
                                />
                            </div>
                            <div>
                                <label className="text-xs text-gray-500 block mb-1">Actual</label>
                                <input
                                    type="number"
                                    value={internalCurr}
                                    onChange={(e) => setInternalCurr(e.target.value)}
                                    className="w-full p-2 rounded border border-orange-200 focus:outline-none focus:ring-2 focus:ring-orange-500 text-sm"
                                    placeholder="Ej. 80"
                                />
                            </div>
                        </div>
                        <div className="mt-2 text-right">
                            <span className="text-xs font-medium text-orange-600">Consumo: {internalDiff} {unit}</span>
                        </div>
                    </div>
                </div>

                {/* Result Preview */}
                <div className="bg-gray-800 text-white rounded-xl p-5 shadow-lg">
                    <div className="flex items-center gap-2 mb-4 opacity-75">
                        <RefreshCw size={16} />
                        <span className="text-xs font-semibold uppercase tracking-wider">A Pagar</span>
                    </div>

                    <div className="flex justify-between items-end">
                        <div>
                            <p className="text-sm opacity-70 mb-1">Casa Adelante</p>
                            <div className="text-3xl font-bold tracking-tight">
                                ${result.frontPayRounded.toLocaleString()}
                            </div>
                        </div>
                        <div className="text-right">
                            <p className="text-sm opacity-70 mb-1">Casa Atrás</p>
                            <div className="text-3xl font-bold tracking-tight text-green-400">
                                ${result.backPayRounded.toLocaleString()}
                            </div>
                        </div>
                    </div>

                    <div className="mt-4 pt-4 border-t border-gray-700 flex justify-between items-center text-sm opacity-80">
                        <span>Consumo Total:</span>
                        <span className="font-mono font-bold">{streetDiff} {unit}</span>
                    </div>

                    {(internalDiff > streetDiff) && (
                        <div className="flex items-center gap-2 text-red-300 text-xs mt-4 bg-red-900/30 p-2 rounded border border-red-500/30">
                            <AlertCircle size={14} />
                            <span>Error: Consumo interno mayor al total.</span>
                        </div>
                    )}
                </div>

                {/* Action Buttons */}
                <div className="flex gap-3">
                    <button
                        onClick={handleClear}
                        className="px-4 py-3 rounded-xl border border-gray-200 text-gray-600 font-medium hover:bg-gray-50 transition-colors"
                    >
                        Limpiar
                    </button>
                    <button
                        onClick={handleSave}
                        disabled={internalDiff > streetDiff || !amount || uploading}
                        className="flex-1 flex items-center justify-center gap-2 bg-blue-600 text-white py-3 rounded-xl font-medium shadow-lg shadow-blue-200 hover:bg-blue-700 transition-all active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {uploading ? <RefreshCw className="animate-spin" size={20} /> : <Save size={20} />}
                        {uploading ? 'Subiendo...' : 'Guardar'}
                    </button>
                </div>
            </div>
        </div>
    );
};
